### ISSUE TITLE
Introduce API definition of Workload

### ISSUE THREAD

**Issue by jsnctl** [cofide/cofide-api-sdk#87]
As a first priority, let's keep this definition as simple as possible. Something like:

```
workload:
  name:
  namespace:
  spiffeid: # provided we can x-ref with registration entry without a chicken-egg scenario
```
